"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.paramMap = exports.ruleParamRequired = void 0;
var confirmed_1 = require("./confirmed");
var requiredIf_1 = require("./requiredIf");
var acceptedIf_1 = require("./acceptedIf");
var after_1 = require("./after");
var before_1 = require("./before");
var array_1 = require("./array");
var afterOrEqual_1 = require("./afterOrEqual");
var beforeOrEqual_1 = require("./beforeOrEqual");
var ruleParamRequired;
(function (ruleParamRequired) {
    ruleParamRequired["confirmed"] = "confirmed";
    ruleParamRequired["required_if"] = "required_if";
    ruleParamRequired["accepted_if"] = "accepted_if";
    ruleParamRequired["after"] = "after";
    ruleParamRequired["after_or_equal"] = "after_or_equal";
    ruleParamRequired["before"] = "before";
    ruleParamRequired["before_or_equal"] = "before_or_equal";
    ruleParamRequired["array"] = "array";
})(ruleParamRequired || (ruleParamRequired = {}));
exports.ruleParamRequired = ruleParamRequired;
var paramMap = {};
exports.paramMap = paramMap;
paramMap[ruleParamRequired.confirmed] = confirmed_1.paramMap;
paramMap[ruleParamRequired.required_if] = requiredIf_1.paramMap;
paramMap[ruleParamRequired.accepted_if] = acceptedIf_1.paramMap;
paramMap[ruleParamRequired.after] = after_1.paramMap;
paramMap[ruleParamRequired.after_or_equal] = afterOrEqual_1.paramMap;
paramMap[ruleParamRequired.before] = before_1.paramMap;
paramMap[ruleParamRequired.before_or_equal] = beforeOrEqual_1.paramMap;
paramMap[ruleParamRequired.array] = array_1.paramMap;
